export const ADD_REVENUE = "ADD_REVENUE";
export const ADD_EXPENSE = "ADD_EXPENSE";
export const DELETE_REVENUE = "DELETE_REVENUE";
export const DELETE_EXPENSE = "DELETE_EXPENSE";
export const EDIT_REVENUE = "EDIT_REVENUE";
export const EDIT_EXPENSE = "EDIT_EXPENSE";
export const TOTALS = "TOTALS";
export const UPDATE_MONTH_TERM = "UPDATE_MONTH_TERM";
export const RESULTS = "RESULTS";
export const FETCH_RESULTS_BEGIN   = 'FETCH_RESULTS_BEGIN';
export const FETCH_RESULTS_SUCCESS = 'FETCH_RESULTS_SUCCESS';
export const FETCH_RESULTS_FAILURE = 'FETCH_RESULTS_FAILURE';


